---
title: "Costa Rican Bulk Rock Compositions"
author: "Julie M. Coulombe"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  word_document:
    fig_caption: yes
  html_document:
    df_print: paged
  pdf_document: default
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE)
cr_data <- read.csv("data/bulk_comp_data.csv")
library(dbplyr)
library(tidyverse)
library(gridExtra)
library(data.table)
library(captioner)
library(furniture)
library(ggpubr)
library(huxtable)
library(flextable)
options(warn = 2)
```

```{r plot setup, include = FALSE}
plot_symbols <- list(
  scale_shape_manual(values = c(7, 8, 10, 11, 21:25)),
    scale_color_manual(values = c("coral1", "chartreuse3", "peachpuff4",
                                  "blue2", "deeppink2", "orchid3",
                                  "royalblue4", "firebrick3", "cyan3"))
)
plot_theme <- list(
  guides(color = guide_legend(override.aes = list(size = 5))), 
    theme(text = element_text(size = 15),
          legend.key.size = unit(1.0, "cm"),
          legend.title = element_text(size = 14),
          plot.title = element_text(hjust = 0.5))
)
```

```{r bulk setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
bulk_data <- read.csv("data/bulk_comp_data_a.csv")
table_nums <- captioner(prefix = "Table")
figure_nums <- captioner(prefix = "Figure")
fig.1 <- figure_nums(name = "fig_1", caption = "TAS Diagram for bulk rock compositions")
fig.2 <- figure_nums(name = "fig_2", caption = "Major elements plotted against SiO2.  All Wt% except Mg#")
fig.3 <- figure_nums(name = "fig_3", caption = "Bulk averages plotted against SiO2.  All wt% except Mg#")
fig.4 <- figure_nums(name = "fig_4", caption = "Comparision of CR1A to CR1B")
fig.5 <- figure_nums(name = "fig_5", caption = "Comparision of CR2A to CR2B")
fig.6 <- figure_nums(name = "fig_6", caption = "Comparision of CR1 to CR2")
tab.1 <- table_nums(name = "tab_1", caption = "Mean averages for major elements")
```

```{r bulk selection, include = FALSE}
bulk_data$Comment <- as.character(bulk_data$Comment)
blk_cr1a <- bulk_data %>%
  filter(grepl("CRA1A", bulk_data$Comment)) %>% 
  mutate("RockName" = "CR1A") 
blk_cr1b <- bulk_data %>%
  filter(grepl("CR1B", bulk_data$Comment)) %>%
  mutate("RockName" = "CR1B")
blk_cr2a_t <- bulk_data %>%
  filter(grepl("CR2A_T", bulk_data$Comment)) %>%
  mutate("RockName" = "CR2A_T")
blk_cr2a_m <- bulk_data %>%
  filter(grepl("CR2A_M", bulk_data$Comment)) %>%
  mutate("RockName" = "CR2A")
blk_cr2b <- bulk_data %>%
  filter(grepl("CR2B", bulk_data$Comment)) %>%
  mutate("RockName" = "CR2B")
blk_cr3 <- bulk_data %>%
  filter(grepl("CR3", bulk_data$Comment)) %>%
  mutate("RockName" = "CR3")
blk_cr4 <- bulk_data %>%
  filter(grepl("CR4", bulk_data$Comment)) %>%
  mutate("RockName" = "CR4")
blk_cr5 <- bulk_data %>%
  filter(grepl("COR5", bulk_data$Comment)) %>%
  mutate("RockName" = "CR5")
blk_cr6 <- bulk_data %>%
  filter(grepl("COR6", bulk_data$Comment)) %>%
  mutate("RockName" = "CR6")
blk_cr7 <- bulk_data %>%
  filter(grepl("CR7", bulk_data$Comment)) %>%
  mutate("RockName" = "CR7")
```

```{r grp blk rocks together, include=FALSE}
blk_data <- rbind(blk_cr1a, blk_cr1b, blk_cr2a_m, blk_cr2b, blk_cr3, blk_cr4, blk_cr5, blk_cr6, blk_cr7)
blk_data <- blk_data[,c(29, 23, 2:15)]
blk_data <- blk_data %>% 
  mutate("MgN" = ((MgO / (40.31)) / ((MgO / (40.31)) + (FeO / (71.85)))) * (100))
blk_data$RockName <- as.factor(blk_data$RockName)
```


```{r blk data constraints, include = FALSE}
blk_data_wt <- blk_data %>%
  select("RockName":"Total", "MgN") %>%  #choose relevant columns
  filter(Total > 98.0 & Total < 101.0) %>%
  filter(SiO2 > 40.0) #select rows based on Total
```


```{r bulk silica vs alkali, echo = FALSE, fig.dim = c(10,6)}
alk_blk_plot <- ggplot(blk_data_wt, aes(x = SiO2, y = Na2O + K2O)) +
  facet_wrap(vars(RockName)) + 
  geom_point(aes(shape = RockName, color = RockName)) +
  labs(title = "Silica vs Alkali", x = "SiO2, Wt%", y = "Na2O + K2O, Wt%") +
  plot_symbols +
  plot_theme
alk_blk_plot
```



```{r bulk si vs mg all, echo = FALSE,fig.dim = c(10,6)}
mg_blk_all <- ggplot(blk_data_wt, aes(x = SiO2, y = MgN)) +
  facet_wrap(vars(RockName)) + 
  geom_point(aes(shape = RockName, color = RockName)) +
  labs(title = "Silica vs Magnesium #", x = "SiO2, Wt%", y = "Mg #") +
  plot_symbols +
  plot_theme
mg_blk_all
```
  
 

```{r bulk si vs fe all, echo = FALSE, fig.dim = c(10,7)}
fe_blk_all <- ggplot(blk_data_wt, aes(x = SiO2, y = FeO)) +
  facet_wrap(vars(RockName)) + 
  geom_point(aes(shape = RockName, color = RockName)) +
  labs(title = "Silica vs Iron", x = "SiO2, Wt%", y = "FeO*, Wt%") +
  plot_symbols + 
  plot_theme
fe_blk_all
```



```{r bulk si vs ca all, echo = FALSE, fig.dim = c(10,7)}
ca_blk_all <- ggplot(blk_data_wt, aes(x = SiO2, y = CaO)) +
  facet_wrap(vars(RockName)) + 
  geom_point(aes(shape = RockName, color = RockName)) +
  labs(title = "Silica vs Calcium", x = "SiO2, Wt%", y = "CaO, Wt%") +
  plot_symbols + 
  plot_theme
ca_blk_all
```
  
```{r bulk si vs k all, echo = FALSE, fig.dim = c(10,7)}
k_blk_all <- ggplot(blk_data_wt, aes(x = SiO2, y = K2O)) +
  facet_wrap(vars(RockName)) + 
  geom_point(aes(shape = RockName, color = RockName)) +
  labs(title = "Silica vs Potassium", x = "SiO2, Wt%", y = "K2O, Wt%") +
  plot_symbols + 
  plot_theme
k_blk_all
```  
  
    
```{r bulk si vs ti all, echo = FALSE, fig.dim = c(10,7)}
ti_blk_all <- ggplot(blk_data_wt, aes(x = SiO2, y = TiO2)) +
  facet_wrap(vars(RockName)) + 
  geom_point(aes(shape = RockName, color = RockName)) +
  labs(title = "Silica vs Titanium", x = "SiO2, Wt%", y = "TiO2, Wt%") +
  plot_symbols + 
  plot_theme
ti_blk_all        
```        
    

```{r bulk si vs al all, echo = FALSE, fig.dim = c(10,7)}
al_blk_all <- ggplot(blk_data_wt, aes(x = SiO2, y = Al2O3)) +
  facet_wrap(vars(RockName)) + 
  geom_point(aes(shape = RockName, color = RockName)) +
  labs(title = "Silica vs Aluminum", x = "SiO2, Wt%", y =  "Al2O3, Wt%") +
  plot_symbols + 
  plot_theme
al_blk_all
```


```{r bulk al vs ti all, echo = FALSE, fig.dim = c(10,7)}
alti_blk_all <- ggplot(blk_data_wt, aes(x = Al2O3, y = TiO2)) +
  facet_wrap(vars(RockName)) + 
  geom_point(aes(shape = RockName, color = RockName)) +
  labs(title = "Aluminum vs Titanium", x = "Al2O3, Wt%", y = "TiO2, Wt%") +
  plot_symbols + 
  plot_theme
alti_blk_all
```
  

```{r tas template, include = FALSE, fig.dim = c(10,5)}
d = data.frame(x = c(40, 80), y = c(0,15))
theme_set(theme_bw(base_size=28))
#makes the TAS template
p <- ggplot(data=d, mapping=aes(x=x, y=y)) +
  geom_blank() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  scale_y_continuous(limits=c(0,15), expand = c(0, 0)) + 
  scale_x_continuous(limits=c(40,80), expand = c(0, 0)) +
  labs(y=expression(Na[2]*O + K[2]*O*~ wt~'%'), x=expression(SiO[2]*~ wt~'%'))+
  annotate("segment", x=45, xend=45, y=1, yend=5)+
  annotate("segment", x=45, xend=52, y=5, yend=5)+
  annotate("segment", x=52, xend=69, y=5, yend=8)+
  annotate("segment", x=76.5, xend=69, y=1, yend=8)+
  annotate("segment", x=69, xend=69, y=8, yend=13)+
  annotate("segment", x=45, xend=61.32, y=5, yend=13.7)+
  annotate("segment", x=52, xend=52, y=1, yend=5)+
  annotate("segment", x=57, xend=57, y=1, yend=5.9)+
  annotate("segment", x=63, xend=63, y=1, yend=6.9)+
  annotate("segment", x=52, xend=49.4, y=5, yend=7.3)+
  annotate("segment", x=57, xend=53.05, y=5.9, yend=9.25)+
  annotate("segment", x=63, xend=57.6, y=6.9, yend=11.7)+
  annotate("segment", x=41, xend=45, y=3, yend=3)+
  annotate("segment", x=41, xend=41, y=1, yend=3)+
  annotate("segment", x=41, xend=41, y=3, yend=7, linetype="dashed")+
  annotate("segment", x=41, xend=45, y=7, yend=9.4, linetype="dashed")+
  annotate("segment", x=45, xend=52.5, y=9.4, yend=14)+
  annotate("segment", x=49.4, xend=45, y=7.3, yend=9.4)+
  annotate("segment", x=53, xend=48.4, y=9.3, yend=11.5)+
  annotate("segment", x=57.6, xend=50.3, y=11.7, yend=15)
```


```{r template with labels, echo = FALSE, fig.dim = c(10,5)}
tas <- p + annotate("text", label = "Basalt", x = 48.5, y = 2, size=4)+
  annotate("text", label = "Basaltic\n andesite", x = 54.3, y = 3.0, size=4)+
  annotate("text", label = "Andesite", x = 60, y = 3.5, size=4)+
  annotate("text", label = "Dacite", x = 67.5, y = 4.2, size=4)+
  annotate("text", label = "Rhyolite", x = 75, y = 7, size=4)+
  annotate("text", label = "Trachy- \n basalt", x = 48.8, y = 5.7, size=4)+
  annotate("text", label = "Basaltic \n trachy- \n andesite", x = 53, y = 7, size=4)+
  annotate("text", label = "Trachy- \n andesite", x = 57.8, y = 8.2, size=4)+
  annotate("text", label = "Trachydacite", x = 65, y = 9, size=4)+
  annotate("text", label = "Trachyte", x = 62.5, y = 11.5, size=4)+
  annotate("text", label = "Picro- \n basalt", x = 43, y = 1.5, size=4)+
  annotate("text", label = "Basanite \n (Ol > 10%)", x = 43.7, y = 6, size=4)+
  annotate("text", label = "Tephrite \n (Ol < 10%)", x = 45, y = 7.8, size=4)+
  annotate("text", label = "Phono- \n tephrite", x = 48.5, y = 9.5, size=4)+
  annotate("text", label = "Tephri- \n phonolite", x = 52.5, y = 11.5, size=4)+
  annotate("text", label = "Phonolite", x = 57, y = 14, size=4)+
  annotate("text", label = "Foidite", x = 45, y = 12, size=4)
```

Plot Alkali by Rock Name - Bulk Composition
```{r alkali by rockname, echo = FALSE, fig.dim = c(10,6.5)}
final_blk_alkplot <- blk_data_wt %>%
  group_by(RockName) %>%
  ggplot(mapping = aes(x = SiO2, y = Na2O + K2O, colour = RockName, legend(cex = 0.75))) +
  geom_point(aes(shape = RockName, color = RockName)) +
  labs(title = "Silica vs Alkali", x = "SiO2, Wt%", y = "Na2O + K2O, Wt%") +
  plot_symbols +
  plot_theme
final_blk_alkplot
```



Overlay Alkali Plot on TAS Diagram
    
    
```{r overlay, echo = FALSE, fig.dim = c(10,6.5), fig.cap=fig.1}
tas +
  geom_point(data = blk_data_wt, aes(x = SiO2, y = Na2O + K2O, shape = RockName, color = RockName)) +
  labs(title = "Bulk Composition on TAS Diagram", x = "SiO2, Wt%", y = "Na2O + K2O, Wt%") +
  plot_symbols +
  plot_theme
```


\newpage

Now to look at Harker Diagrams of all rocks plotted together


```{r si vs mg bulk, echo = FALSE, fig.dim = c(10,7)}
mg_blk_plot <- blk_data_wt %>%
  group_by(RockName) %>%
  ggplot(mapping = aes(SiO2, MgN, colour = RockName)) +
  geom_point(aes(shape = RockName, color = RockName, size = 3)) +
  labs(title = "Silica vs Magnesium Number by rock", x = "SiO2, Wt%", y = "Mg #") +
  plot_symbols +
  plot_theme
mg_blk_plot + scale_x_continuous(limits = c(45, 65))
```




```{r si vs fe bulk, echo = FALSE, fig.dim = c(10,7)}
fe_blk_plot <- blk_data_wt %>%
  group_by(RockName) %>%
  ggplot(mapping = aes(SiO2, FeO, colour = RockName)) +
  geom_point(aes(shape = RockName, color = RockName, size = 3)) +
  labs(title = "Silica vs Iron by rock", x = "SiO2, Wt%", y = "FeO*, Wt%") +
  plot_symbols +
  plot_theme
fe_blk_plot + scale_x_continuous(limits = c(45, 65))
```



```{r si vs ca bulk, echo = FALSE, fig.dim = c(10,7)}
ca_blk_plot <- blk_data_wt %>%
  group_by(RockName) %>%
  ggplot(mapping = aes(SiO2, CaO, colour = RockName)) +
  geom_point(aes(shape = RockName, color = RockName, size = 3)) +
  labs(title = "Silica vs Calcium by rock", x = "SiO2, Wt%", y = "CaO, Wt%") +
  plot_symbols +
  plot_theme
ca_blk_plot + scale_x_continuous(limits = c(45, 65))
```


```{r si vs k bulk, echo = FALSE, fig.dim = c(10,7)}
k_blk_plot <- blk_data_wt %>%
  group_by(RockName) %>%
  ggplot(mapping = aes(SiO2, K2O, colour = RockName)) +
  geom_point(aes(shape = RockName, color = RockName, size = 3)) +
  labs(title = "Silica vs Potassium by rock", x = "SiO2, Wt%", y = "K2O, Wt%") +
  plot_symbols +
  plot_theme
k_blk_plot + scale_x_continuous(limits = c(45, 65))
```



```{r si vs ti bulk, echo = FALSE, fig.dim = c(10,7)}
ti_blk_plot <- blk_data_wt %>%
  group_by(RockName) %>%
  ggplot(mapping = aes(SiO2, TiO2, colour = RockName)) +
  geom_point(aes(shape = RockName, color = RockName, size = 3)) +
  labs(title = "Silica vs Titanium by rock", x = "SiO2, Wt%", y = "TiO2, Wt%") +
  plot_symbols +
  plot_theme
ti_blk_plot + scale_x_continuous(limits = c(45, 65))
```

```{r si vs al bulk, echo = FALSE, fig.dim = c(10,7)}
al_blk_plot <- blk_data_wt %>%
  group_by(RockName) %>%
  ggplot(mapping = aes(SiO2, Al2O3, colour = RockName)) +
  geom_point(aes(shape = RockName, color = RockName, size = 3)) +
  labs(title = "Silica vs Aluminum by rock", x = "SiO2, Wt%", y = "Al2O3, Wt%") +
  plot_symbols +
  plot_theme
al_blk_plot + scale_x_continuous(limits = c(45, 65))
```

 

```{r al vs ti bulk, echo = FALSE,  fig.dim = c(10,7)}
alti_blk_plot <- blk_data_wt %>%
  group_by(RockName) %>%
  ggplot(mapping = aes(Al2O3, TiO2, colour = RockName)) +
  geom_point(aes(shape = RockName, color = RockName, size = 3)) +
  labs(title = "Aluminum vs Titanium by rock", x = "Al2O3, Wt%", y = "TiO2, Wt%") +
  plot_symbols +
  plot_theme
alti_blk_plot
```
      
               
\newpage

        
 
```{r si vs mg fig, echo = FALSE, fig.dim = c(10,7)}
mg_blk_plotp <- blk_data_wt %>%  ##need to reprint all plots w altered themes to pull together.
  group_by(RockName) %>%
  ggplot(mapping = aes(SiO2, MgN, colour = RockName)) +
  geom_point(aes(shape = RockName, color = RockName)) +
  labs(x = "SiO2, Wt%", y = "Mg#") +
  plot_symbols
mg_blk_plotp <- mg_blk_plotp + 
    guides(color = guide_legend(override.aes = list(size = 10))) + 
    theme(text = element_text(size = 18),
          legend.key.size = unit(1.5, "cm"),
          legend.title = element_text(size = 20),
          legend.text = element_text(size = 20))
```




```{r si vs fe fig, echo = FALSE, fig.dim = c(10,7)}
fe_blk_plotp <- blk_data_wt %>%
  group_by(RockName) %>%
  ggplot(mapping = aes(SiO2, FeO, colour = RockName)) +
  geom_point(aes(shape = RockName, color = RockName)) +
  labs(x = "SiO2, Wt%", y = "FeO*, Wt%") +
  plot_symbols +
  theme(text = element_text(size = 18))
```



```{r si vs ca fig, echo = FALSE, fig.dim = c(10,7)}
ca_blk_plotp <- blk_data_wt %>%
  group_by(RockName) %>%
  ggplot(mapping = aes(SiO2, CaO, colour = RockName)) +
  geom_point(aes(shape = RockName, color = RockName)) +
  labs(x = "SiO2, Wt%", y = "CaO, Wt%") +
  plot_symbols +
  theme(text = element_text(size = 18))
```


```{r si vs k fig, echo = FALSE, fig.dim = c(10,7)}
k_blk_plotp <- blk_data_wt %>%
  group_by(RockName) %>%
  ggplot(mapping = aes(SiO2, K2O, colour = RockName)) +
  geom_point(aes(shape = RockName, color = RockName)) +
  labs(x = "SiO2, Wt%", y = "K2O, Wt%") +
  plot_symbols +
  theme(text = element_text(size = 18))
```


```{r si vs ti fig, echo = FALSE, fig.dim = c(10,7)}
ti_blk_plotp <- blk_data_wt %>%
  group_by(RockName) %>%
  ggplot(mapping = aes(SiO2, TiO2, colour = RockName)) +
  geom_point(aes(shape = RockName, color = RockName)) +
  labs(x = "SiO2, Wt%", y = "TiO2, Wt%") +
  plot_symbols +
  theme(text = element_text(size = 18))
```


    
```{r si vs al fig, echo = FALSE, fig.dim = c(10,7)}
al_blk_plotp <- blk_data_wt %>%
  group_by(RockName) %>%
  ggplot(mapping = aes(SiO2, Al2O3, colour = RockName)) +
  geom_point(aes(shape = RockName, color = RockName)) +
  labs(x = "SiO2, Wt%", y = "Al2O3, Wt%") +
  plot_symbols +
  theme(text = element_text(size = 18))
```


```{r al vs ti fig, echo = FALSE, fig.dim = c(10,7)}
alti_blk_plotp <- blk_data_wt %>%
  group_by(RockName) %>%
  ggplot(mapping = aes(Al2O3, TiO2, colour = RockName)) +
  geom_point(aes(shape = RockName, color = RockName)) +
  labs(x = "Al2O3, Wt%", y = "TiO2, Wt%") +
  plot_symbols +
  theme(text = element_text(size = 18))
```

```{r fig 2 plot, echo = FALSE, fig.dim = c(10,12), fig.cap=fig.2} 
ggarrange(mg_blk_plotp, fe_blk_plotp, ca_blk_plotp, k_blk_plotp, ti_blk_plotp, al_blk_plotp, ncol = 2, nrow = 3, common.legend = TRUE, legend = "bottom")
```

\newpage

```{r bulk avg table, include=FALSE, fig.dim = c(10,7)}                              
blk_avg <- blk_data_wt %>%
  group_by(RockName) %>%
  summarise("SiO2 m" = mean(SiO2), "SiO2 sd" = sd(SiO2),
            "TiO2 m" = mean(TiO2), "TiO2 sd" = sd(TiO2),
            "Al2O3 m" = mean(Al2O3), "Al2O3 sd" = sd(Al2O3),
            "Cr m" = mean(Cr2O3), "Cr sd" = sd(Cr2O3),
            "MgO m" = mean(MgO), "MgO sd" = sd(MgO),
            "CaO m" = mean(CaO), "CaO sd" = sd(CaO),
            "MnO m" = mean(MnO), "MnO sd" = sd(MnO),
            "FeO m" = mean(FeO), "FeO sd" = sd(FeO),
            "Na2O m" = mean(Na2O), "Na2O sd" = sd(Na2O),
            "K2O m" = mean(K2O), "K2O sd" = sd(K2O),
            "S m" = mean(S), "S sd" = sd(S),
            "P2O5 m" = mean(P2O5), "P2O5 sd" = sd(P2O5),
            "MgN m" = mean(MgN), "MgN sd" = sd(MgN),
            "Total m" = mean(Total), "Total sd" = sd(Total), .groups = "keep")
  
```


```{r bulk avg si/alk, echo=FALSE, fig.dim = c(10,7)} 
alk_avg_blkplot <- blk_avg %>%
  ggplot(mapping = aes(x = `SiO2 m`, y = `Na2O m` + `K2O m`, ymin = `Na2O m` + `K2O m` - `Na2O sd` + `K2O sd`, ymax = `Na2O m` + `K2O m` + `Na2O sd` + `K2O sd`, colour = RockName, legend(cex = 0.75))) +
  geom_point(aes(shape = RockName, color = RockName, size = 2)) +
  geom_errorbar() +
  labs(title = "Average Alkali per Rock", x = "SiO2, Wt%", y = "Na2O + K2O, Wt%") +
  plot_symbols + 
  plot_theme
alk_avg_blkplot
```



\newpage


```{r bulk avg mg, echo = FALSE, fig.show='hide'} 
mg_avg_blkplot <- blk_avg %>%
  ggplot(mapping = aes(`SiO2 m`, `MgN m`, ymin = `MgN m` - `MgN sd`, ymax = `MgN m` + `MgN sd`, colour = RockName)) +
  geom_point(aes(shape = RockName, color = RockName, size = 3)) +
  geom_errorbar() +
  labs(x = "SiO2, Wt%", y = "Mg #") +
  plot_symbols +
  guides(color = guide_legend(override.aes = list(size = 6))) + 
  theme(text = element_text(size = 18),
          legend.key.size = unit(1.5, "cm"),
          legend.title = element_text(size = 20),
          legend.text = element_text(size = 20))
mg_avg_blkplot + scale_x_continuous(limits = c(50,60))
```

```{r bulk avg fe, echo = FALSE, fig.show='hide'}
fe_avg_blkplot <- blk_avg %>%
  group_by(RockName) %>%
  ggplot(mapping = aes(`SiO2 m`, `FeO m`, ymin = `FeO m` - `FeO sd`, ymax = `FeO m` + `FeO sd`, colour = RockName)) +
  geom_point(aes(shape = RockName, color = RockName, size = 3)) +
  geom_errorbar() + 
  labs(x = "SiO2, Wt%", y = "FeO*, Wt%") +
  plot_symbols +
  theme(text = element_text(size = 18))
fe_avg_blkplot + scale_x_continuous(limits = c(50, 60))
```
 
```{r bulk avg ca, echo = FALSE, fig.show='hide'} 
ca_avg_blkplot <- blk_avg %>%
  group_by(RockName) %>%
  ggplot(mapping = aes(`SiO2 m`, `CaO m`, ymin = `CaO m` - `CaO sd`, ymax = `CaO m` + `CaO sd`, colour = RockName)) +
  geom_point(aes(shape = RockName, color = RockName, size = 3)) +
  geom_errorbar() +
  labs(x = "SiO2, Wt%", y = "CaO, Wt%") +
  plot_symbols +
  theme(text = element_text(size = 18))
ca_avg_blkplot + scale_x_continuous(limits = c(50, 60))
```

```{r bulk avg K2O, echo = FALSE, fig.show='hide'} 
k_avg_blkplot <- blk_avg %>%
  group_by(RockName) %>%
  ggplot(mapping = aes(`SiO2 m`, `K2O m`, ymin = `K2O m` - `K2O sd`, ymax = `K2O m` + `K2O sd`, colour = RockName)) +
  geom_point(aes(shape = RockName, color = RockName, size = 3)) +
  geom_errorbar() + 
  labs(x = "SiO2, Wt%", y = "K2O, Wt%") +
  plot_symbols +
  theme(text = element_text(size = 18))
k_avg_blkplot + scale_x_continuous(limits = c(50, 60))
```


```{r bulk avg ti, echo = FALSE, fig.show='hide'} 
ti_avg_blkplot <- blk_avg %>%
  group_by(RockName) %>%
  ggplot(mapping = aes(`SiO2 m`, `TiO2 m`, ymin = `TiO2 m` - `TiO2 sd`, ymax = `TiO2 m` + `TiO2 sd`, colour = RockName)) +
  geom_point(aes(shape = RockName, color = RockName, size = 3)) +
  geom_errorbar() +
  labs(x = "SiO2, Wt%", y = "TiO2, Wt%") +
  plot_symbols +
  theme(text = element_text(size = 18))
ti_avg_blkplot + scale_x_continuous(limits = c(50, 60))
```


```{r bulk avg al, echo = FALSE, fig.show='hide'}
al_avg_blkplot <- blk_avg %>%
  group_by(RockName) %>%
  ggplot(mapping = aes(`SiO2 m`, `Al2O3 m`, ymin = `Al2O3 m` - `Al2O3 sd`, ymax = `Al2O3 m` + `Al2O3 sd`, colour = RockName)) +
  geom_point(aes(shape = RockName, color = RockName, size = 3)) +
  geom_errorbar() +
  labs(x = "SiO2, Wt%", y = "Al2O3, Wt%") +
  plot_symbols +
  theme(text = element_text(size = 18))
al_avg_blkplot + scale_x_continuous(limits = c(50, 60))
```

```{r bulk avg alti, echo = FALSE, fig.show='hide', fig.dim = c(10,7)}
alti_avg_blkplot <- blk_avg %>%
  group_by(RockName) %>%
  ggplot(mapping = aes(`Al2O3 m`, `TiO2 m`, ymin = `TiO2 m` - `TiO2 sd`, ymax = `TiO2 m` + `TiO2 sd`, colour = RockName)) +
  geom_point(aes(shape = RockName, color = RockName, size = 3)) +
  geom_errorbar() +
  labs(title = "Bulk Average Aluminum vs Titanium by Rock", x = "Al2O3, Wt%", y = "TiO2, Wt%") +
  plot_symbols +
  plot_theme
alti_avg_blkplot
```

```{r fig 3 avg plot, echo = FALSE, fig.dim = c(10,12), fig.cap=fig.3} 
ggarrange(mg_avg_blkplot, fe_avg_blkplot, ca_avg_blkplot, k_avg_blkplot,
          ti_avg_blkplot, al_avg_blkplot, ncol = 2, nrow = 3, common.legend = TRUE, legend = "bottom")
```



\newpage

                  
```{r cr1 bulk - Si/Alk, echo = FALSE, fig.show='hide'}
cr1a_cr1b_blkalk <- blk_data_wt %>%
  filter(grepl("CR1", blk_data_wt$RockName)) %>%
  ggplot(aes(SiO2, Na2O + K2O, colour = RockName)) + 
  geom_point(aes(shape = RockName, color = RockName)) +
  labs(x = "SiO2, Wt%", y = "Na2O + K2O, Wt%") +
  scale_shape_manual(values = c(7, 8)) + 
  scale_color_manual(values = c("coral1", "chartreuse3")) + 
  guides(color = guide_legend(override.aes = list(size = 10))) +
  theme(text = element_text(size = 18),
          legend.key.size = unit(1.5, "cm"),
          legend.title = element_text(size = 20),
          legend.text = element_text(size = 20))
```  
 


```{r cr1 bulk - Si/MgN, echo = FALSE, fig.show='hide'}
cr1a_cr1b_blkmg <- blk_data_wt %>%
  filter(grepl("CR1", blk_data_wt$RockName)) %>%
  ggplot(aes(SiO2, MgN, colour = RockName)) + 
  geom_point(aes(shape = RockName, color = RockName)) +
  labs(x = "SiO2, Wt%", y = "Mg #") +
  scale_shape_manual(values = c(7, 8)) + 
  scale_color_manual(values = c("coral1", "chartreuse3")) +
  theme(text = element_text(size = 18))
```



```{r cr1 bulk - Si/Fe, echo = FALSE, fig.show='hide'}
cr1a_cr1b_blkfe <- blk_data_wt %>%
  filter(grepl("CR1", blk_data_wt$RockName)) %>%
  ggplot(aes(SiO2, FeO, colour = RockName)) + 
  geom_point(aes(shape = RockName, color = RockName)) +
  labs(x = "SiO2, Wt%", y = "FeO*, Wt%") +
  scale_shape_manual(values = c(7, 8)) + 
  scale_color_manual(values = c("coral1", "chartreuse3")) +
  theme(text = element_text(size = 18))
```

```{r cr1 bulk - Si/Ca, echo = FALSE, fig.show='hide'}
cr1a_cr1b_blkca <- blk_data_wt %>%
  filter(grepl("CR1", blk_data_wt$RockName)) %>%
  ggplot(aes(SiO2, CaO, colour = RockName)) + 
  geom_point(aes(shape = RockName, color = RockName)) +
  labs(x = "SiO2, Wt%", y = "CaO, Wt%") +
  scale_shape_manual(values = c(7, 8)) + 
  scale_color_manual(values = c("coral1", "chartreuse3")) +
  theme(text = element_text(size = 18))
```


```{r fig 4 cr1 plot, echo = FALSE, fig.dim = c(10,8.0), fig.cap=fig.4} 
ggarrange(cr1a_cr1b_blkalk, cr1a_cr1b_blkmg, cr1a_cr1b_blkfe, cr1a_cr1b_blkca, ncol = 2, nrow = 2, common.legend = TRUE, legend = "bottom")
```




```{r cr1 bulk - Al/Ti, echo = FALSE, fig.dim = c(10,6.5)}
cr1a_cr1b_blkalti <- blk_data_wt %>%
  filter(grepl("CR1", blk_data_wt$RockName)) %>%
  ggplot(aes(Al2O3, TiO2, colour = RockName)) + 
  geom_point(aes(shape = RockName, color = RockName, size = 3)) +
  labs(title = "Aluminum vs Titanium for CR1", x = "Al2O3, Wt%", y = "TiO2, Wt%") +
  scale_shape_manual(values = c(7, 8)) + 
  scale_color_manual(values = c("coral1", "chartreuse3")) + 
  plot_theme
cr1a_cr1b_blkalti
```  



        
```{r cr2 bulk - Si/Alk, include=FALSE}
cr2a_cr2b_blkalk <- blk_data_wt %>%
  filter(grepl("CR2", blk_data_wt$RockName)) %>%
  ggplot(aes(SiO2, Na2O + K2O, colour = RockName)) + 
  geom_point(aes(shape = RockName, color = RockName)) +
  labs(x = "SiO2, Wt%", y = "Na2O + K2O, Wt%") +
  scale_shape_manual(values = c(10, 11)) + 
  scale_color_manual(values = c("peachpuff4", "blue2")) + 
  guides(color = guide_legend(override.aes = list(size = 10))) +
  theme(text = element_text(size = 18),
          legend.key.size = unit(1.5, "cm"),
          legend.title = element_text(size = 20),
          legend.text = element_text(size = 20))
```


```{r cr2 bulk - Si/MgN, include=FALSE}
cr2a_cr2b_blkmg <- blk_data_wt %>%
  filter(grepl("CR2", blk_data_wt$RockName)) %>%
  ggplot(aes(SiO2, MgN, colour = RockName)) + 
  geom_point(aes(shape = RockName, color = RockName)) +
  labs(x = "SiO2, Wt%", y = "Mg #") +
  scale_shape_manual(values = c(10, 11)) + 
  scale_color_manual(values = c("peachpuff4", "blue2")) + 
  theme(text = element_text(size = 18))
```


```{r cr2 bulk - Si/Fe, include=FALSE}
cr2a_cr2b_blkfe <- blk_data_wt %>%
  filter(grepl("CR2", blk_data_wt$RockName)) %>%
  ggplot(aes(SiO2, FeO, colour = RockName)) + 
  geom_point(aes(shape = RockName, color = RockName, size = 3)) +
  labs(x = "SiO2, Wt%", y = "FeO*, Wt%") + 
   scale_shape_manual(values = c(10, 11)) + 
  scale_color_manual(values = c("peachpuff4", "blue2")) + 
  plot_theme
```

```{r cr2 bulk - Si/Ca, include=FALSE}
cr2a_cr2b_blkca <- blk_data_wt %>%
  filter(grepl("CR2", blk_data_wt$RockName)) %>%
  ggplot(aes(SiO2, CaO, colour = RockName)) + 
  geom_point(aes(shape = RockName, color = RockName, size = 3)) +
  labs(x = "SiO2, Wt%", y = "CaO, Wt%") + 
   scale_shape_manual(values = c(10, 11)) + 
  scale_color_manual(values = c("peachpuff4", "blue2")) + 
  plot_theme
```


```{r fig 5 cr2 plot, echo = FALSE, fig.dim = c(10,7.5), fig.cap=fig.5} 
ggarrange(cr2a_cr2b_blkalk, cr2a_cr2b_blkmg, cr2a_cr2b_blkfe, cr2a_cr2b_blkca, ncol = 2, nrow = 2, common.legend = TRUE, legend = "bottom")
```

```{r cr2 bulk - Al/Ti, echo=FALSE, fig.dim = c(10,6.5)} 
cr2a_cr2b_blkalti <- blk_data_wt %>%
  filter(grepl("CR2", blk_data_wt$RockName)) %>%
  ggplot(aes(Al2O3, TiO2, colour = RockName)) + 
  geom_point(aes(shape = RockName, color = RockName, size = 3)) +
  labs(title = "Aluminum vs Titanium for CR2", x = "Al2O3, Wt%", y = "TiO2, Wt%") +
  scale_shape_manual(values = c(10, 11)) + 
  scale_color_manual(values = c("peachpuff4", "blue2")) + 
  plot_theme
cr2a_cr2b_blkalti
```

\newpage


```{r CR1 to CR2 bulk - Si/Alk, include=FALSE}
cr1_cr2_blkalk <- blk_data_wt %>%
  filter(grepl("CR[1-2]", blk_data_wt$RockName)) %>%
  ggplot(aes(SiO2, Na2O + K2O, colour = RockName)) + 
  geom_point(aes(shape = RockName, color = RockName, size = 3)) +
  labs(x = "SiO2, Wt%", y = "Na2O + K2O, Wt%") +
  scale_shape_manual(values = c(7, 7, 10, 10)) + 
  scale_color_manual(values = c("coral1", "coral1", "blue2", "blue2")) + 
  plot_theme
```


```{r 1 to 2 bulk - Si/MgN, include=FALSE}
cr1_cr2_blkmg <- blk_data_wt %>%
  filter(grepl("CR[1-2]", blk_data_wt$RockName)) %>%
  ggplot(aes(SiO2, MgN, colour = RockName)) + 
  geom_point(aes(shape = RockName, color = RockName, size = 3)) +
  labs(x = "SiO2, Wt%", y = "Mg #") +
  scale_shape_manual(values = c(7, 7, 10, 10)) + 
  scale_color_manual(values = c("coral1", "coral1", "blue2", "blue2")) + 
  guides(color = guide_legend(override.aes = list(size = 5))) +
  plot_theme
```


```{r 1 to 2 bulk - Si/Fe, include=FALSE} 
cr1_cr2_blkfe <- blk_data_wt %>%
  filter(grepl("CR[1-2]", blk_data_wt$RockName)) %>%
  ggplot(aes(SiO2, FeO, colour = RockName)) + 
  geom_point(aes(shape = RockName, color = RockName, size = 3)) +
  labs(x = "SiO2, Wt%", y = "FeO*, Wt%") + 
  scale_shape_manual(values = c(7, 7, 10, 10)) + 
  scale_color_manual(values = c("coral1", "coral1", "blue2", "blue2")) + 
  guides(color = guide_legend(override.aes = list(size = 5))) +
  plot_theme
```


```{r 1 to 2 bulk - Si/Ca, include=FALSE} 
cr1_cr2_blkca <- blk_data_wt %>%
  filter(grepl("CR[1-2]", blk_data_wt$RockName)) %>%
  ggplot(aes(SiO2, CaO, colour = RockName)) + 
  geom_point(aes(shape = RockName, color = RockName, size = 3)) +
  labs(x = "SiO2, Wt%", y = "CaO, Wt%") + 
  scale_shape_manual(values = c(7, 7, 10, 10)) + 
  scale_color_manual(values = c("coral1", "coral1", "blue2", "blue2")) + 
  guides(color = guide_legend(override.aes = list(size = 5))) +
  plot_theme
```


```{r fig 6 cr1 2 plot, echo = FALSE, fig.dim = c(10,7.5), fig.cap=fig.6} 
ggarrange(cr1_cr2_blkalk, cr1_cr2_blkmg, cr1_cr2_blkfe, cr1_cr2_blkca, ncol = 2, nrow = 2, common.legend = TRUE, legend = "bottom")
```

```{r 1 to 2 bulk - Al/Ti, echo=FALSE, fig.dim = c(10,6.5)}
cr1_cr2_blkalti <- blk_data_wt %>%
  filter(grepl("CR[1-2]", blk_data_wt$RockName)) %>%
  ggplot(aes(Al2O3, TiO2, colour = RockName)) + 
  geom_point(aes(shape = RockName, color = RockName, size = 3)) +
  labs(title = "Aluminum vs Titanium for CR1  & CR2", x = "Al2O3, Wt%", y = "TiO2, Wt%") +
  scale_shape_manual(values = c(7, 7, 10, 10)) + 
  scale_color_manual(values = c("coral1", "coral1", "blue2", "blue2")) + 
  plot_theme
cr1_cr2_blkalti
```
    
\newpage

Table indicating mean averages for elements by rock
```{r table1, include = FALSE}
bulk_avg <- blk_data_wt %>%
  group_by(RockName) %>%
    summarise(n = n(),
            "SiO2 m" = mean(SiO2), "SiO2 sd" = sd(SiO2),
            "TiO2 m" = mean(TiO2), "TiO2 sd" = sd(TiO2),
            "Al2O3 m" = mean(Al2O3), "Al2O3 sd" = sd(Al2O3),
            "Cr m" = mean(Cr2O3), "Cr sd" = sd(Cr2O3),
            "MgO m" = mean(MgO), "MgO sd" = sd(MgO),
            "CaO m" = mean(CaO), "CaO sd" = sd(CaO),
            "MnO m" = mean(MnO), "MnO sd" = sd(MnO),
            "FeO m" = mean(FeO), "FeO sd" = sd(FeO),
            "Na2O m" = mean(Na2O), "Na2O sd" = sd(Na2O),
            "K2O m" = mean(K2O),  "K2O sd" = sd(K2O),
            "S m" = mean(S),  "S sd" = sd(S),
            "P2O5 m" = mean(P2O5), "P2O5 sd" = sd(P2O5),
            "MgN m" = mean(MgN),  "MgN sd" = sd(MgN),
            "Total m" = mean(Total), "Total sd" = sd(Total), .groups = "keep")
bulk_avg2 <- as.data.frame(bulk_avg)
bulk_avg3 <- bulk_avg2[,-1]
rownames(bulk_avg3) <- bulk_avg2[, 1]
bulk_avg_tran <- transpose(bulk_avg3)
rownames(bulk_avg_tran) <- colnames(bulk_avg3)
colnames(bulk_avg_tran) <- rownames(bulk_avg3)
```
  
```{r print table1, echo=FALSE}
knitr::kable(bulk_avg_tran, "simple", digits = 3)
```
   
\newpage

       

```{r table2, include = FALSE, fig.dim = c(5,20)}
bulk_avg_m <- blk_data_wt %>%
  group_by(RockName) %>%
  summarise(n = n(), "SiO2" = mean(SiO2), "TiO2" = mean(TiO2),
            "Al2O3" = mean(Al2O3), "Cr" = mean(Cr2O3),
            "MgO" = mean(MgO), "CaO" = mean(CaO), "MnO" = mean(MnO),
            "FeO" = mean(FeO), "Na2O" = mean(Na2O), "K2O" = mean(K2O),
            "S" = mean(S), "P2O5" = mean(P2O5), "MgN" = mean(MgN),
            "Total" = mean(Total), .groups = "keep")
bulk_avg_m2 <- as.data.frame(bulk_avg_m) 
bulk_avg_m3 <- bulk_avg_m2[,-1]
rownames(bulk_avg_m3) <- bulk_avg_m2[, 1]
bulk_avg_mtran <- transpose(bulk_avg_m3)
rownames(bulk_avg_mtran) <- colnames(bulk_avg_m3)
colnames(bulk_avg_mtran) <- rownames(bulk_avg_m3)
```

```{r print table2, echo=FALSE, fig.cap=tab.1}
knitr::kable(bulk_avg_mtran, "simple", digits = 3, caption = "Mean averages for major elements")
```
